// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC86JnTcdKcMuLm-vvsqmQOhQ2VMzqUkg',
    appId: '1:165863315426:web:ad7e9fffee5543343c0bbb',
    messagingSenderId: '165863315426',
    projectId: 'bridgelt',
    authDomain: 'bridgelt.firebaseapp.com',
    storageBucket: 'bridgelt.appspot.com',
    measurementId: 'G-8LGYSNKH6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgiei0cSeRGZ7u3gjihYfKGzF7gHc_wAY',
    appId: '1:165863315426:android:a964a48b7845ad283c0bbb',
    messagingSenderId: '165863315426',
    projectId: 'bridgelt',
    storageBucket: 'bridgelt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8MbgA-7SvbhMVK-2nSJCz1r_gJy-Fi3I',
    appId: '1:165863315426:ios:33342d19d5fe8b1a3c0bbb',
    messagingSenderId: '165863315426',
    projectId: 'bridgelt',
    storageBucket: 'bridgelt.appspot.com',
    iosBundleId: 'com.example.bridgelt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8MbgA-7SvbhMVK-2nSJCz1r_gJy-Fi3I',
    appId: '1:165863315426:ios:4cf3e913fc05e3a63c0bbb',
    messagingSenderId: '165863315426',
    projectId: 'bridgelt',
    storageBucket: 'bridgelt.appspot.com',
    iosBundleId: 'com.example.bridgelt.RunnerTests',
  );
}
